version: "3.8"
services:
  flask-app:
    build: ./flask-application
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  nginx:
    image: 
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf